environment:
  PYPI_USERNAME: konstin
  PYO3_PACK_PASSWORD:
    secure: Re9Dc8ZtgroxOc1PSO/0Hu7h9sUwjPdrufdr2Ycc3ho=
  matrix:
    - CHANNEL: stable
      TARGET: x86_64-pc-windows-msvc
    - CHANNEL: stable
      TARGET: i686-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %CHANNEL% --default-host %TARGET%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

test_script:
  - #cargo test

before_deploy:
  - pip install pyo3-pack

deploy_script:
  - pyo3-pack publish -u %PYPI_USERNAME% -b bin --release -r https://test.pypi.org/legacy/

build: off
